pull_request_rules:
  - name: automatic merge for nt9-bot pull requests affecting build.sbt
    conditions:
      - author=nt9-bot[bot]
      - check-success~=Build and Test*
      - "#files=1"
      - files=build.sbt
    actions:
      merge:
        method: rebase
  - name: automatic merge for nt9-bot pull requests affecting project plugins.sbt
    conditions:
      - author=nt9-bot[bot]
      - check-success~=Build and Test*
      - "#files=1"
      - files=project/plugins.sbt
    actions:
      merge:
        method: rebase
  - name: automatic merge for nt9-bot pull requests affecting .scalafmt.conf
    conditions:
      - author=nt9-bot[bot]
      - check-success~=Build and Test*
      - "#files=1"
      - files=.scalafmt.conf
    actions:
      merge:
        method: rebase
  - name: automatic merge for nt9-bot pull requests affecting project build.properties
    conditions:
      - author=nt9-bot[bot]
      - check-success~=Build and Test*
      - "#files=1"
      - files=project/build.properties
    actions:
      merge:
        method: rebase
