pull_request_rules:
  - name: automatic merge for scala-steward pull requests affecting build.sbt
    conditions:
      - author=scala-steward
      - check-success~=Build and Test*
      - "#files=1"
      - files=build.sbt
    actions:
      merge:
        method: rebase
  - name: automatic merge for scala-steward pull requests affecting project plugins.sbt
    conditions:
      - author=scala-steward
      - check-success~=Build and Test*
      - "#files=1"
      - files=project/plugins.sbt
    actions:
      merge:
        method: rebase
  - name: automatic merge for scala-steward pull requests affecting .scalafmt.conf
    conditions:
      - author=scala-steward
      - check-success~=Build and Test*
      - "#files=1"
      - files=.scalafmt.conf
    actions:
      merge:
        method: rebase
  - name: automatic merge for scala-steward pull requests affecting project build.properties
    conditions:
      - author=scala-steward
      - check-success~=Build and Test*
      - "#files=1"
      - files=project/build.properties
    actions:
      merge:
        method: rebase
