pull_request_rules:
  - name: automatic merge for scala-steward pull requests affecting build.sbt
    conditions:
      - author=scala-steward
      - check-success~=Build and Test*
      - "#files=1"
      - files=build.sbt
    actions:
      merge:
        method: merge